#!/usr/bin/env sh

set -e

# Variables
FOLDER_PATH="$(dirname "$0")/_server/.next"

# Legacy variable names compatibility
: ${WEB_SDK_LICENSE_KEY:=${PSPDFKIT_STANDALONE_LICENSE_KEY}}
export WEB_SDK_LICENSE_KEY
: ${WEB_SDK_LIB_SERVE_STRATEGY:=${PSPDFKIT_LIB_SERVE_STRATEGY}}
export WEB_SDK_LIB_SERVE_STRATEGY
: ${WEB_SDK_LIB_EXPLICIT_URL:=${PSPDFKIT_LIB_EXPLICIT_URL}}
export WEB_SDK_LIB_EXPLICIT_URL

: ${DOCUMENT_ENGINE_EXTERNAL_URL:=${PSPDFKIT_SERVER_EXTERNAL_URL}}
export DOCUMENT_ENGINE_EXTERNAL_URL
: ${DOCUMENT_ENGINE_INTERNAL_URL:=${PSPDFKIT_SERVER_INTERNAL_URL}}
export DOCUMENT_ENGINE_INTERNAL_URL
: ${DOCUMENT_ENGINE_API_AUTH_TOKEN:=${PSPDFKIT_SERVER_API_AUTH_TOKEN}}
export DOCUMENT_ENGINE_API_AUTH_TOKEN

: ${NUTRIENT_AIA_URL:=${PSPDFKIT_AIA_URL}}
export NUTRIENT_AIA_URL
: ${NUTRIENT_AIA_JWT_PRIVATE_KEY:=${AIA_JWT_PRIVATE_KEY}}
export NUTRIENT_AIA_JWT_PRIVATE_KEY

: ${NUTRIENT_DWS_API_KEY:=${PSPDFKIT_API_KEY}}
export NUTRIENT_DWS_API_KEY
: ${NUTRIENT_DWS_API_URL:=${PSPDFKIT_API_URL}}
export NUTRIENT_DWS_API_URL

# Reporting
echo "Substituting environment variables in all files in $FOLDER_PATH"
if [ -n "$WEB_SDK_LICENSE_KEY" ]; then
  echo "WEB_SDK_LICENSE_KEY: ****"
else
  echo "WEB_SDK_LICENSE_KEY:"
fi
echo "DOCUMENT_ENGINE_EXTERNAL_URL: ${DOCUMENT_ENGINE_EXTERNAL_URL}"
echo "DOCUMENT_ENGINE_INTERNAL_URL: ${DOCUMENT_ENGINE_INTERNAL_URL}"
echo "WEB_SDK_LIB_SERVE_STRATEGY: ${WEB_SDK_LIB_SERVE_STRATEGY}"
echo "WEB_SDK_LIB_EXPLICIT_URL: ${WEB_SDK_LIB_EXPLICIT_URL}"
echo "NUTRIENT_AIA_URL: ${NUTRIENT_AIA_URL}"

# Loop through all files
find "$FOLDER_PATH" -type f | while read -r file; do
  # Apply multiple search-replace pairs
  sed -i -e "s~WEB_SDK_LICENSE_KEY_PLACEHOLDER~${WEB_SDK_LICENSE_KEY}~g" \
         -e "s~DOCUMENT_ENGINE_EXTERNAL_URL_PLACEHOLDER~${DOCUMENT_ENGINE_EXTERNAL_URL:-"5000"}~g" \
         -e "s~WEB_SDK_LIB_SERVE_STRATEGY_PLACEHOLDER~${WEB_SDK_LIB_SERVE_STRATEGY:-"static"}~g" \
         -e "s~WEB_SDK_LIB_EXPLICIT_URL_PLACEHOLDER~${WEB_SDK_LIB_EXPLICIT_URL:-"http://localhost:8080"}~g" \
         -e "s~NUTRIENT_AIA_URL_PLACEHOLDER~${NUTRIENT_AIA_URL}~g" "$file"
done

echo "Environment variables substituted in all files in $FOLDER_PATH"

dumb-init node "$@"
